openapi: 3.1.0
externalDocs:
  description: Documentation of the OpenAPI Document Library of the ISA² IPS REST API Core Profile
  url: https://joinup.ec.europa.eu/collection/api4dt/solution/...

info:
  title: "ISA² IPS REST API Core Profile - OpenAPI Document Specification"
  version: 1.0.0

components:
  headers:
    edel-message-sig:
      description: The custom header used for carrying the detached signature for signing the HTTP Message
      schema:
        $ref: '#/components/schemas/jws-compact-detached'

    edel-payload-sig:
      description: The custom header used for carrying the detached signature for signing the payload
      schema:
        $ref: '#/components/schemas/jws-compact-detached'

    deprecation:
      description: Deprecation HTTP Response Header following the Internet-Draft "The Deprecation HTTP Header Field"
        (https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-deprecation-header-01)
      schema:
        $ref: '#/components/schemas/date-value'

    sunset:
      description: Sunset HTTP Response Header following [RFC8594]. For every operation it MUST be set to the date the
        API is to be sunset
      schema:
        $ref: '#/components/schemas/date-value'

  schemas:

    jws-compact-detached:
      type: string
      format: jws-compact-detached
      pattern: ^[A-Za-z0-9_-]+\.(?:\.[A-Za-z0-9_-]+)$

    date-value:
      type: string
      format: date

    problem:
      "$schema": https://json-schema.org/draft-07/schema#
      "$id": https://joinup.ec.europa.eu/collection/api4dt/solution/.../messaging.schema.json
      title: A Problem Details object following RFC 7807
      description: A Problem Details object following RFC 7807 defined by the ISA² IPS REST API Core Profile
        to messages
      type: object
      properties:
        type:
          type: string
          format: uri
          description: An URI reference that identifies the problem type. When dereferenced, it SHOULD provide
            human-readable documentation for the problem type (e.g. using HTML).
          default: about:blank
        title:
          type: string
          description: A short summary of the problem type, written in English and readable for engineers (usually not
            suited for non technical stakeholders and not localized).
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 200
          exclusiveMaximum: 600
          example: 503
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example:
        instance:
          type: string
          format: uri-reference
          description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield
            further information if dereferenced.
      required:
      - title
      - type
      - status

      additionalProperties: true
